import type { Metadata } from "next"
import { Chivo } from "next/font/google"
import "./globals.css"
import React from "react"
import Navbar from "@/components/nav/navbar"

const chivo = Chivo({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
	title: "Sauce Store",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={chivo.className}>
				<Navbar />

				{children}
			</body>
		</html>
	)
}
